### PR TITLE
Qa/psalm

### LINKED ISSUE #11: Psalm integration
### Feature Request

|    Q        |   A
|------------ | ------
| QA    | yes

#### Summary

As decided during the [Technical-Steering-Committee Meeting on August 3rd, 2020](https://github.com/laminas/technical-steering-committee/blob/main/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-static-analysis-tooling), Laminas wants to implement [vimeo/psalm](https://github.com/vimeo/psalm) in all packages.

Implementing psalm is quite easy.

#### Required
- [ ] Create a `psalm.xml` in the project root
- [ ] Copy and paste the contents from this [psalm.xml.dist](https://github.com/mezzio/repo-template/blob/6124090610ef1c6d6b0c80a063cafacc3ec68f38/psalm.xml.dist)
- [ ] Run `$ composer require --dev vimeo/psalm`
- [ ] Run `$ vendor/bin/psalm --set-baseline=psalm-baseline.xml`
- [ ] Add a composer script `static-analysis` with the command `psalm --shepherd --stats`
- [ ] Add a new line to `script:` in `.travis.yml`: `- if [[ $TEST_COVERAGE == 'true' ]]; then composer static-analysis ; fi`
- [ ] Remove phpstan from the project (`phpstan.neon.dist`, `.travis.yml` entry, `composer.json` `require-dev` and `scripts`)

##### Optional
- [ ] Fix as many psalm errors as possible.

### PR DESCRIPTION
**Pull request by superrosko**
|    Q          |   A
|-------------- | ------
| QA            | yes

### Description

 - Create a psalm.xml in the project root
 - Copy and paste the contents from this psalm.xml.dist and fix projectFiles
 - Run $ composer --dev require vimeo/psalm
 - Run $ composer require --dev psalm/plugin-phpunit
 - Run $ vendor/bin/psalm --set-baseline=psalm-baseline.xml
 - Add a composer script static-analysis with the command psalm --shepherd --stats
 - Add a new line to script: in .travis.yml: - if [[ $TEST_COVERAGE == 'true' ]]; then composer static-analysis ; fi
 - Remove phpstan from the project (phpstan.neon.dist, .travis.yml entry, composer.json require-dev and scripts)

Closes #11

### CODE REVIEW

**Comment by superrosko** [comment]
@boesing, if the PRs is correct, then you can put a label hacktoberfest-accepted on it?

**Comment by boesing** [comment]
hey @superrosko, thanks for contributing!
sadly, travis is not executing anymore. That is because the `travis.yml` changes you've applied are not valid. Please re-check and see how to format the matrix entry. 

You need to apply these changes to all your pull requests. After this, I am happy to label your PRs and merge them! 💪🏻

You can verify your travis.yml [here](http://yaml-online-parser.appspot.com/) for compatibility. 

When everything is okay, you will see travis listed below the comment section in the "checks" area next to the DCO check 👍🏻

**Comment by superrosko** [comment]
@boesing, thanks for pointing out the error, i fixed it for all my PRs

**Comment by superrosko** [comment]
psalm/plugin-phpunit min version 0.1.0 require vimeo/psalm version ^3.0, and vimeo/psalm ^3.0 require php ^7.0

only vimeo/psalm version 1.x can use php ^5.6||^7.0 and vimeo/psalm version 2.x can use php ^7.0

if we need support php 5.6 we must use vimeo/psalm 1.x and don't use psalm/plugin-phpunit anywhere

**Comment by superrosko** [comment]
@boesing, PR is correct? Or should all tests complete correctly?
To complete the tests, you need to remove the 5.6 and 7.0 posts.
Install the minimum version 7.1, because this is the minimum version for vimeo/psalm and psalm/plugin-phpunit?

**Comment by boesing** [comment]
@superrosko We need another PR in here which solves #12 
After this, we can rebase this PR against that implementation and are good to go 👍 

Thanks for implementing this!

**Pull request merged**
